### ISSUE TITLE
Possible problem with parsing from Array[Byte] with Utf8 chars

### ISSUE THREAD

**Issue by ktoso** [spray/spray-json#162] opened 2015-09-03 09:18 UTC
As seen in https://github.com/akka/akka/issues/18389

The string:

```
{"title":"ÇatÇat Kitapları","parentName":"Çocuk Kitapları"}
```

Unmarshalled incorrectly when parsed from byte array, but correctly when string was given.

**Comment by jrudolph** [comment] 2015-11-03 09:10
This is most likely a duplicate of #148. Closing for now...

**Closed by jrudolph** 2015-11-03 09:10 UTC
